// <auto-generated />
using System;
using LR.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LR.Core.Data.Migrations
{
    [DbContext(typeof(LRDbContext))]
    [Migration("20260822144227_AddDetectedMmprojPathToLocalModel")]
    partial class AddDetectedMmprojPathToLocalModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LR.Core.Models.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowAllModels")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("ApiKeys", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ApiKeyModelPreset", b =>
                {
                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelPresetId")
                        .HasColumnType("TEXT");

                    b.HasKey("ApiKeyId", "ModelPresetId");

                    b.HasIndex("ModelPresetId");

                    b.ToTable("ApiKeyModelPresets", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ApiRequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackendResponsePayload")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<double?>("FirstTokenLatencyMs")
                        .HasColumnType("REAL");

                    b.Property<int>("GeneratedTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncomingPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStreaming")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutgoingPayloadSummary")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptTokensProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalLatencyMs")
                        .HasColumnType("REAL");

                    b.Property<string>("TranslatedPayload")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasQueued")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PresetId");

                    b.HasIndex("ServerInstanceId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Protocol", "Timestamp");

                    b.ToTable("ApiRequestLogs", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.BackendConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanionAppPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentSetupCommand")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraSettings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GpuBackendType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LlamaCppExecutableFolderPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerInstanceId")
                        .IsUnique();

                    b.ToTable("BackendConfigs", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.LocalModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllKvPairsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Architecture")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BlockCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BosTokenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatTemplate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContextLength")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedMmprojPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmbeddingLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EosTokenId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FeedForwardLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GgufModelName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HeadCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HfFilename")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("HfRepoId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("HfRevision")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KvHeadCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterSize")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuantizationLevel")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("RopeFreqBase")
                        .HasColumnType("REAL");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.ToTable("LocalModels", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ModelLibrarySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HuggingFaceApiToken")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootFolder")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModelLibrarySettings", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ModelPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BatchSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CachePrompt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CacheRam")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CacheReuse")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheTypeK")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheTypeV")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatTemplate")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatTemplateKwargs")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ContBatching")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ContextShift")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContextSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlVector")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ControlVectorLayerEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ControlVectorLayerStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlVectorScaled")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("CpuMoe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Device")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DryAllowedLength")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("DryBase")
                        .HasColumnType("REAL");

                    b.Property<float?>("DryMultiplier")
                        .HasColumnType("REAL");

                    b.Property<int?>("DryPenaltyLastN")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DrySequenceBreaker")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<float?>("DynatempExp")
                        .HasColumnType("REAL");

                    b.Property<float?>("DynatempRange")
                        .HasColumnType("REAL");

                    b.Property<string>("Fit")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FitCtx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FitTarget")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlashAttention")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<float?>("FrequencyPenalty")
                        .HasColumnType("REAL");

                    b.Property<string>("GgufArchitecture")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("GgufChatTemplate")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GgufContextLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GgufEmbeddingLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GgufModelName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GgufParameterSize")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("GgufQuantizationLevel")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("GgufRopeFreqBase")
                        .HasColumnType("REAL");

                    b.Property<int?>("GpuLayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IgnoreEos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageMaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageMinTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Jinja")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KeepN")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("KvOffload")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("KvUnified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoadMode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lora")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoraScaled")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MainGpu")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("MinP")
                        .HasColumnType("REAL");

                    b.Property<int?>("Mirostat")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("MirostatEta")
                        .HasColumnType("REAL");

                    b.Property<float?>("MirostatTau")
                        .HasColumnType("REAL");

                    b.Property<string>("Mmproj")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("MmprojAuto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MmprojDevice")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("MmprojOffload")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MmprojUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MtmdBatchMaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NCpuMoe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OverrideTensor")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Parallel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PredictN")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("PresencePenalty")
                        .HasColumnType("REAL");

                    b.Property<string>("Reasoning")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReasoningBudget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasoningBudgetMessage")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningEffort")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningFormat")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ReasoningPreserve")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Repack")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepeatLastN")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("RepeatPenalty")
                        .HasColumnType("REAL");

                    b.Property<float?>("RopeFreqBase")
                        .HasColumnType("REAL");

                    b.Property<float?>("RopeFreqScale")
                        .HasColumnType("REAL");

                    b.Property<float?>("RopeScale")
                        .HasColumnType("REAL");

                    b.Property<string>("RopeScalingType")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("SamplerSeq")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Samplers")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServerInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SleepIdleSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("SlotPromptSimilarity")
                        .HasColumnType("REAL");

                    b.Property<int?>("SpecDraftGpuLayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecDraftModel")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpecDraftNMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpecDraftNMin")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("SpecDraftPMin")
                        .HasColumnType("REAL");

                    b.Property<float?>("SpecDraftPSplit")
                        .HasColumnType("REAL");

                    b.Property<int?>("SpecDraftThreads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecDraftTypeK")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecDraftTypeV")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SplitMode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<float?>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<string>("TensorSplit")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Threads")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThreadsBatch")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Timeout")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TopK")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("TopNSigma")
                        .HasColumnType("REAL");

                    b.Property<float?>("TopP")
                        .HasColumnType("REAL");

                    b.Property<float?>("TypicalP")
                        .HasColumnType("REAL");

                    b.Property<int?>("UbatchSize")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("XtcProbability")
                        .HasColumnType("REAL");

                    b.Property<float?>("XtcThreshold")
                        .HasColumnType("REAL");

                    b.Property<float?>("YarnAttnFactor")
                        .HasColumnType("REAL");

                    b.Property<float?>("YarnBetaFast")
                        .HasColumnType("REAL");

                    b.Property<float?>("YarnBetaSlow")
                        .HasColumnType("REAL");

                    b.Property<float?>("YarnExtFactor")
                        .HasColumnType("REAL");

                    b.Property<int?>("YarnOrigCtx")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("ServerInstanceId");

                    b.ToTable("ModelPresets", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ModelStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextLengthUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContextMaxLength")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DraftAcceptanceRate")
                        .HasColumnType("REAL");

                    b.Property<int>("DraftAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DraftGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DraftMeanLen")
                        .HasColumnType("REAL");

                    b.Property<double>("FirstTokenLatencyMs")
                        .HasColumnType("REAL");

                    b.Property<int>("GeneratedTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GenerationMs")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<double>("PromptProcessingMs")
                        .HasColumnType("REAL");

                    b.Property<int>("PromptTokensProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServerInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalLatencyMs")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PresetId", "Timestamp");

                    b.HasIndex("ServerInstanceId", "Timestamp");

                    b.ToTable("ModelStatistics", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.RoutingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BackendType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetServerInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetServerInstanceId");

                    b.ToTable("RoutingRules", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ServerInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActivePresetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Engine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastErrorTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRestarts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestartCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivePresetId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ServerInstances", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ServerLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerInstanceId", "Timestamp");

                    b.ToTable("ServerLogs", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.StoredResponse", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Background")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnInputItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnOutputItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousResponseId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Store")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolChoiceJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PreviousResponseId");

                    b.ToTable("StoredResponses", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ApiKeyModelPreset", b =>
                {
                    b.HasOne("LR.Core.Models.ApiKey", "ApiKey")
                        .WithMany("AllowedPresets")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LR.Core.Models.ModelPreset", "ModelPreset")
                        .WithMany()
                        .HasForeignKey("ModelPresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");

                    b.Navigation("ModelPreset");
                });

            modelBuilder.Entity("LR.Core.Models.ApiRequestLog", b =>
                {
                    b.HasOne("LR.Core.Models.ModelPreset", "Preset")
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LR.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany()
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Preset");

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.BackendConfig", b =>
                {
                    b.HasOne("LR.Core.Models.ServerInstance", "ServerInstance")
                        .WithOne("Config")
                        .HasForeignKey("LR.Core.Models.BackendConfig", "ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.ModelPreset", b =>
                {
                    b.HasOne("LR.Core.Models.LocalModel", "Model")
                        .WithMany("Presets")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LR.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany("Presets")
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.ModelStatistics", b =>
                {
                    b.HasOne("LR.Core.Models.ModelPreset", "Preset")
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LR.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany()
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preset");

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.RoutingRule", b =>
                {
                    b.HasOne("LR.Core.Models.ServerInstance", "TargetServerInstance")
                        .WithMany()
                        .HasForeignKey("TargetServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.ServerInstance", b =>
                {
                    b.HasOne("LR.Core.Models.ModelPreset", "ActivePreset")
                        .WithMany()
                        .HasForeignKey("ActivePresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivePreset");
                });

            modelBuilder.Entity("LR.Core.Models.ServerLog", b =>
                {
                    b.HasOne("LR.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany("Logs")
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.ApiKey", b =>
                {
                    b.Navigation("AllowedPresets");
                });

            modelBuilder.Entity("LR.Core.Models.LocalModel", b =>
                {
                    b.Navigation("Presets");
                });

            modelBuilder.Entity("LR.Core.Models.ServerInstance", b =>
                {
                    b.Navigation("Config");

                    b.Navigation("Logs");

                    b.Navigation("Presets");
                });
#pragma warning restore 612, 618
        }
    }
}
