// <auto-generated />
using System;
using LR.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LR.Core.Migrations
{
    [DbContext(typeof(LRDbContext))]
    [Migration("20260805172143_AddGgufMetadataToPreset")]
    partial class AddGgufMetadataToPreset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LR.Core.Models.BackendConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanionAppPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentSetupCommand")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraSettings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GpuBackendType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LlamaCppExecutableFolderPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerInstanceId")
                        .IsUnique();

                    b.ToTable("BackendConfigs", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ModelPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BatchSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CachePrompt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CacheRam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheTypeK")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheTypeV")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatTemplate")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ContBatching")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContextSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Device")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DryAllowedLength")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("DryBase")
                        .HasColumnType("REAL");

                    b.Property<float?>("DryMultiplier")
                        .HasColumnType("REAL");

                    b.Property<int?>("DryPenaltyLastN")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("DynatempExp")
                        .HasColumnType("REAL");

                    b.Property<float?>("DynatempRange")
                        .HasColumnType("REAL");

                    b.Property<string>("Fit")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlashAttention")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<float?>("FrequencyPenalty")
                        .HasColumnType("REAL");

                    b.Property<string>("GgufArchitecture")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("GgufChatTemplate")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GgufContextLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GgufEmbeddingLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GgufModelName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GgufParameterSize")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("GgufQuantizationLevel")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("GgufRopeFreqBase")
                        .HasColumnType("REAL");

                    b.Property<int?>("GpuLayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IgnoreEos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageMaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageMinTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Jinja")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KeepN")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("KvOffload")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoadMode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lora")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MainGpu")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("MinP")
                        .HasColumnType("REAL");

                    b.Property<int?>("Mirostat")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("MirostatEta")
                        .HasColumnType("REAL");

                    b.Property<float?>("MirostatTau")
                        .HasColumnType("REAL");

                    b.Property<string>("Mmproj")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Parallel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PredictN")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("PresencePenalty")
                        .HasColumnType("REAL");

                    b.Property<string>("Reasoning")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReasoningBudget")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Repack")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepeatLastN")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("RepeatPenalty")
                        .HasColumnType("REAL");

                    b.Property<float?>("RopeFreqBase")
                        .HasColumnType("REAL");

                    b.Property<float?>("RopeFreqScale")
                        .HasColumnType("REAL");

                    b.Property<float?>("RopeScale")
                        .HasColumnType("REAL");

                    b.Property<string>("RopeScalingType")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServerInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpecDraftGpuLayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecDraftModel")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpecDraftNMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpecDraftNMin")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("SpecDraftPMin")
                        .HasColumnType("REAL");

                    b.Property<int?>("SpecDraftThreads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecDraftTypeK")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecDraftTypeV")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SplitMode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<float?>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<string>("TensorSplit")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Threads")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThreadsBatch")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Timeout")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TopK")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("TopNSigma")
                        .HasColumnType("REAL");

                    b.Property<float?>("TopP")
                        .HasColumnType("REAL");

                    b.Property<float?>("TypicalP")
                        .HasColumnType("REAL");

                    b.Property<int?>("UbatchSize")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("XtcProbability")
                        .HasColumnType("REAL");

                    b.Property<float?>("XtcThreshold")
                        .HasColumnType("REAL");

                    b.Property<float?>("YarnAttnFactor")
                        .HasColumnType("REAL");

                    b.Property<float?>("YarnBetaFast")
                        .HasColumnType("REAL");

                    b.Property<float?>("YarnBetaSlow")
                        .HasColumnType("REAL");

                    b.Property<float?>("YarnExtFactor")
                        .HasColumnType("REAL");

                    b.Property<int?>("YarnOrigCtx")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerInstanceId");

                    b.ToTable("ModelPresets", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ModelStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextLengthUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContextMaxLength")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DraftAcceptanceRate")
                        .HasColumnType("REAL");

                    b.Property<int>("DraftAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DraftGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DraftMeanLen")
                        .HasColumnType("REAL");

                    b.Property<double>("FirstTokenLatencyMs")
                        .HasColumnType("REAL");

                    b.Property<int>("GeneratedTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GenerationMs")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<double>("PromptProcessingMs")
                        .HasColumnType("REAL");

                    b.Property<int>("PromptTokensProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServerInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalLatencyMs")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PresetId", "Timestamp");

                    b.HasIndex("ServerInstanceId", "Timestamp");

                    b.ToTable("ModelStatistics", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.RoutingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BackendType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetServerInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetServerInstanceId");

                    b.ToTable("RoutingRules", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ServerInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActivePresetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Engine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastErrorTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRestarts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestartCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivePresetId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ServerInstances", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ServerLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerInstanceId", "Timestamp");

                    b.ToTable("ServerLogs", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.BackendConfig", b =>
                {
                    b.HasOne("LR.Core.Models.ServerInstance", "ServerInstance")
                        .WithOne("Config")
                        .HasForeignKey("LR.Core.Models.BackendConfig", "ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.ModelPreset", b =>
                {
                    b.HasOne("LR.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany("Presets")
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.ModelStatistics", b =>
                {
                    b.HasOne("LR.Core.Models.ModelPreset", "Preset")
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LR.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany()
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preset");

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.RoutingRule", b =>
                {
                    b.HasOne("LR.Core.Models.ServerInstance", "TargetServerInstance")
                        .WithMany()
                        .HasForeignKey("TargetServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.ServerInstance", b =>
                {
                    b.HasOne("LR.Core.Models.ModelPreset", "ActivePreset")
                        .WithMany()
                        .HasForeignKey("ActivePresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivePreset");
                });

            modelBuilder.Entity("LR.Core.Models.ServerLog", b =>
                {
                    b.HasOne("LR.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany("Logs")
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.ServerInstance", b =>
                {
                    b.Navigation("Config");

                    b.Navigation("Logs");

                    b.Navigation("Presets");
                });
#pragma warning restore 612, 618
        }
    }
}
