// <auto-generated />
using System;
using LR.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LR.Core.Migrations
{
    [DbContext(typeof(LRDbContext))]
    partial class LRDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LR.Core.Models.BackendConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanionAppPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraSettings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GpuBackendType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LlamaCppExecutableFolderPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerInstanceId")
                        .IsUnique();

                    b.ToTable("BackendConfigs", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ModelPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GpuLayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerInstanceId");

                    b.ToTable("ModelPresets", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ModelStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextLengthUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContextMaxLength")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FirstTokenLatencyMs")
                        .HasColumnType("REAL");

                    b.Property<int>("GeneratedTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GenerationMs")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<double>("PromptProcessingMs")
                        .HasColumnType("REAL");

                    b.Property<int>("PromptTokensProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServerInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalLatencyMs")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PresetId", "Timestamp");

                    b.HasIndex("ServerInstanceId", "Timestamp");

                    b.ToTable("ModelStatistics", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.RoutingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BackendType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetServerInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetServerInstanceId");

                    b.ToTable("RoutingRules", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.ServerInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActivePresetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Engine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivePresetId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ServerInstances", (string)null);
                });

            modelBuilder.Entity("LR.Core.Models.BackendConfig", b =>
                {
                    b.HasOne("LR.Core.Models.ServerInstance", "ServerInstance")
                        .WithOne("Config")
                        .HasForeignKey("LR.Core.Models.BackendConfig", "ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.ModelPreset", b =>
                {
                    b.HasOne("LR.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany("Presets")
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.ModelStatistics", b =>
                {
                    b.HasOne("LR.Core.Models.ModelPreset", "Preset")
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LR.Core.Models.ServerInstance", "ServerInstance")
                        .WithMany()
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preset");

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.RoutingRule", b =>
                {
                    b.HasOne("LR.Core.Models.ServerInstance", "TargetServerInstance")
                        .WithMany()
                        .HasForeignKey("TargetServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetServerInstance");
                });

            modelBuilder.Entity("LR.Core.Models.ServerInstance", b =>
                {
                    b.HasOne("LR.Core.Models.ModelPreset", "ActivePreset")
                        .WithMany()
                        .HasForeignKey("ActivePresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivePreset");
                });

            modelBuilder.Entity("LR.Core.Models.ServerInstance", b =>
                {
                    b.Navigation("Config");

                    b.Navigation("Presets");
                });
#pragma warning restore 612, 618
        }
    }
}
