using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LR.Core.Models;

/// <summary>
/// Log entry for an API request that passed through the router.
/// Captures the full lifecycle: incoming request, translation, backend response, and outgoing response.
/// </summary>
[Table("ApiRequestLogs")]
public class ApiRequestLog
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// When the request was received.
    /// </summary>
    [Required]
    public DateTimeOffset Timestamp { get; set; } = DateTimeOffset.UtcNow;

    // ── Request identification ───────────────────────────────────────

    /// <summary>
    /// The API protocol used (OpenAI, Claude, Ollama).
    /// </summary>
    [Required]
    public ApiProtocol Protocol { get; set; }

    /// <summary>
    /// The endpoint path that was called (e.g. "/v1/chat/completions").
    /// </summary>
    [Required, MaxLength(256)]
    public string EndpointPath { get; set; } = string.Empty;

    /// <summary>
    /// The model name extracted from the incoming request.
    /// </summary>
    [MaxLength(128)]
    public string? ModelName { get; set; }

    // ── Routing context ──────────────────────────────────────────────

    /// <summary>
    /// The server instance that handled the request (if routed).
    /// </summary>
    [ForeignKey(nameof(ServerInstance))]
    public Guid? ServerInstanceId { get; set; }

    public virtual ServerInstance? ServerInstance { get; set; }

    /// <summary>
    /// The preset used for this request.
    /// </summary>
    [ForeignKey(nameof(Preset))]
    public Guid? PresetId { get; set; }

    public virtual ModelPreset? Preset { get; set; }

    /// <summary>
    /// The API key that authenticated this request (if any). Null when API-key auth is disabled
    /// or the request was unauthenticated. Set null (not cascade-deleted) if the key is removed.
    /// </summary>
    [ForeignKey(nameof(ApiKey))]
    public Guid? ApiKeyId { get; set; }

    public virtual ApiKey? ApiKey { get; set; }

    // ── Payload chain (the full transformation pipeline) ─────────────

    /// <summary>
    /// Raw JSON body received from the client.
    /// </summary>
    [Column(TypeName = "TEXT")]
    public string IncomingPayload { get; set; } = string.Empty;

    /// <summary>
    /// The payload after translation, as sent to the backend provider (RouteRequest.Payload).
    /// </summary>
    [Column(TypeName = "TEXT")]
    public string? TranslatedPayload { get; set; }

    /// <summary>
    /// Raw response from the backend (for non-streaming: full body; for streaming: summary only unless LogFullPayloads is enabled).
    /// </summary>
    [Column(TypeName = "TEXT")]
    public string? BackendResponsePayload { get; set; }

    /// <summary>
    /// Summary of the response sent back to the client.
    /// For streaming responses this contains metadata rather than the full stream.
    /// </summary>
    [Column(TypeName = "TEXT")]
    public string? OutgoingPayloadSummary { get; set; }

    // ── Response ID (for OpenAI response_id / previous_response_id) ──

    /// <summary>
    /// The response ID generated by the router (e.g. "chatcmpl-...").
    /// Stored for future correlation with OpenAI's response_id / previous_response_id feature.
    /// </summary>
    [MaxLength(128)]
    public string? ResponseId { get; set; }

    // ── Metrics & status ─────────────────────────────────────────────

    /// <summary>
    /// HTTP status code returned to the client.
    /// </summary>
    public int StatusCode { get; set; } = 200;

    /// <summary> Whether this was a streaming request. </summary>
    public bool IsStreaming { get; set; }

    /// <summary> Whether the request had to be queued (no server immediately available). </summary>
    public bool WasQueued { get; set; }

    /// <summary> Total latency from receive to final response in milliseconds. </summary>
    public double? TotalLatencyMs { get; set; }

    /// <summary> Time to first token (for streaming) or total latency (for non-streaming). </summary>
    public double? FirstTokenLatencyMs { get; set; }

    /// <summary> Number of prompt tokens processed. </summary>
    public int PromptTokensProcessed { get; set; }

    /// <summary> Number of generated output tokens. </summary>
    public int GeneratedTokenCount { get; set; }

    /// <summary> Error message if the request failed. </summary>
    [MaxLength(4096)]
    public string? ErrorMessage { get; set; }

    // ── Derived display helpers ───────────────────────────────────────

    [NotMapped]
    public string ProtocolBadge => Protocol switch
    {
        ApiProtocol.OpenAI => "OpenAI",
        ApiProtocol.Claude => "Claude",
        ApiProtocol.Ollama => "Ollama",
        _ => Protocol.ToString()
    };

    [NotMapped]
    public string StatusDisplay => ErrorMessage != null ? "Error" : StatusCode switch
    {
        >= 200 and < 300 => "OK",
        >= 300 and < 400 => "Redirect",
        >= 400 and < 500 => "Client Error",
        _ => "Server Error"
    };
}
