using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LR.Core.Models;

/// <summary>
/// Per-request statistics log entry for model inference performance tracking.
/// </summary>
[Table("ModelStatistics")]
public class ModelStatistics
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// The server instance that handled the request.
    /// </summary>
    [Required, ForeignKey(nameof(ServerInstance))]
    public Guid ServerInstanceId { get; set; }

    /// <summary>
    /// The preset used for this request (if any).
    /// </summary>
    public Guid? PresetId { get; set; }

    /// <summary>
    /// The API key that authenticated the client for this request (if any). Null when API-key
    /// auth is disabled or the request was unauthenticated. Set null (not cascade-deleted) if
    /// the key is later removed, so historical stats survive.
    /// </summary>
    [ForeignKey(nameof(ApiKey))]
    public Guid? ApiKeyId { get; set; }

    /// <summary>
    /// When the request was processed.
    /// </summary>
    [Required]
    public DateTimeOffset Timestamp { get; set; } = DateTimeOffset.UtcNow;

    // --- Prompt metrics ---

    /// <summary>
    /// Number of tokens in the input prompt that were processed.
    /// </summary>
    public int PromptTokensProcessed { get; set; }

    /// <summary>
    /// Time in milliseconds spent processing the input prompt.
    /// </summary>
    public double PromptProcessingMs { get; set; }

    /// <summary>
    /// Prompt processing throughput (tokens/sec) as reported directly by the backend.
    /// Zero when the backend didn't report a rate (older rows, non-llama.cpp providers).
    /// See <see cref="RouteResponse.PromptTokensPerSecond"/> for why this is preferred over
    /// recomputing from the token count and elapsed time.
    /// </summary>
    public double PromptTokensPerSecReported { get; set; }

    /// <summary>
    /// Derived: tokens per second for prompt processing. Uses the backend-reported rate when
    /// available, falling back to <c>PromptTokensProcessed / PromptProcessingMs</c> for rows
    /// recorded before that figure was captured (that fallback over-reports when prompt caching
    /// is in play, since the token count includes cache hits the time doesn't cover).
    /// </summary>
    [NotMapped]
    public double PromptTokensPerSec =>
        PromptTokensPerSecReported > 0
            ? PromptTokensPerSecReported
            : PromptProcessingMs > 0 ? (PromptTokensProcessed / PromptProcessingMs) * 1000 : 0;

    // --- Generation metrics ---

    /// <summary>
    /// Number of output tokens generated by the model.
    /// </summary>
    public int GeneratedTokenCount { get; set; }

    /// <summary>
    /// Time in milliseconds spent generating output tokens.
    /// </summary>
    public double GenerationMs { get; set; }

    /// <summary>
    /// Derived: tokens per second for generation.
    /// </summary>
    [NotMapped]
    public double GenTokensPerSec =>
        GenerationMs > 0 ? (GeneratedTokenCount / GenerationMs) * 1000 : 0;

    // --- Latency ---

    /// <summary>
    /// Total end-to-end latency in milliseconds.
    /// </summary>
    public double TotalLatencyMs { get; set; }

    /// <summary>
    /// Time from request sent to first output token received (TTFT).
    /// </summary>
    public double FirstTokenLatencyMs { get; set; }

    // --- Context ---

    /// <summary>
    /// How much of the context window was used for this request.
    /// </summary>
    public int ContextLengthUsed { get; set; }

    /// <summary>
    /// Maximum context length configured on the preset (for reference).
    /// </summary>
    public int ContextMaxLength { get; set; }

    // --- Speculative decoding metrics (only populated when speculative decoding is active) ---

    /// <summary>
    /// Draft acceptance rate for speculative decoding (0.0 to 1.0). Null if not used.
    /// </summary>
    public double? DraftAcceptanceRate { get; set; }

    /// <summary>
    /// Number of draft tokens accepted during speculative decoding.
    /// </summary>
    public int DraftAccepted { get; set; }

    /// <summary>
    /// Number of draft tokens generated during speculative decoding.
    /// </summary>
    public int DraftGenerated { get; set; }

    /// <summary>
    /// Mean length of accepted draft sequences during speculative decoding.
    /// </summary>
    public double? DraftMeanLen { get; set; }

    // --- Navigation properties ---

    public ServerInstance? ServerInstance { get; set; }
    public ModelPreset? Preset { get; set; }
    public ApiKey? ApiKey { get; set; }
}
