using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LR.Core.Models;

/// <summary>
/// Per-request statistics log entry for model inference performance tracking.
/// </summary>
[Table("ModelStatistics")]
public class ModelStatistics
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// The server instance that handled the request.
    /// </summary>
    [Required, ForeignKey(nameof(ServerInstance))]
    public Guid ServerInstanceId { get; set; }

    /// <summary>
    /// The preset used for this request (if any).
    /// </summary>
    public Guid? PresetId { get; set; }

    /// <summary>
    /// When the request was processed.
    /// </summary>
    [Required]
    public DateTimeOffset Timestamp { get; set; } = DateTimeOffset.UtcNow;

    // --- Prompt metrics ---

    /// <summary>
    /// Number of tokens in the input prompt that were processed.
    /// </summary>
    public int PromptTokensProcessed { get; set; }

    /// <summary>
    /// Time in milliseconds spent processing the input prompt.
    /// </summary>
    public double PromptProcessingMs { get; set; }

    /// <summary>
    /// Derived: tokens per second for prompt processing.
    /// </summary>
    [NotMapped]
    public double PromptTokensPerSec =>
        PromptProcessingMs > 0 ? (PromptTokensProcessed / PromptProcessingMs) * 1000 : 0;

    // --- Generation metrics ---

    /// <summary>
    /// Number of output tokens generated by the model.
    /// </summary>
    public int GeneratedTokenCount { get; set; }

    /// <summary>
    /// Time in milliseconds spent generating output tokens.
    /// </summary>
    public double GenerationMs { get; set; }

    /// <summary>
    /// Derived: tokens per second for generation.
    /// </summary>
    [NotMapped]
    public double GenTokensPerSec =>
        GenerationMs > 0 ? (GeneratedTokenCount / GenerationMs) * 1000 : 0;

    // --- Latency ---

    /// <summary>
    /// Total end-to-end latency in milliseconds.
    /// </summary>
    public double TotalLatencyMs { get; set; }

    /// <summary>
    /// Time from request sent to first output token received (TTFT).
    /// </summary>
    public double FirstTokenLatencyMs { get; set; }

    // --- Context ---

    /// <summary>
    /// How much of the context window was used for this request.
    /// </summary>
    public int ContextLengthUsed { get; set; }

    /// <summary>
    /// Maximum context length configured on the preset (for reference).
    /// </summary>
    public int ContextMaxLength { get; set; }

    // --- Navigation properties ---

    public ServerInstance? ServerInstance { get; set; }
    public ModelPreset? Preset { get; set; }
}
