namespace LR.Core.Models;

/// <summary>
/// Wraps an inference response payload together with performance metadata returned by the backend provider.
/// </summary>
public class RouteResponse
{
    /// <summary>
    /// The text/content returned from the inference request.
    /// </summary>
    public string Payload { get; set; } = string.Empty;

    /// <summary>
    /// Number of tokens in the input prompt that were processed.
    /// </summary>
    public int PromptTokensProcessed { get; set; }

    /// <summary>
    /// Number of output tokens generated by the model.
    /// </summary>
    public int GeneratedTokenCount { get; set; }

    /// <summary>
    /// Time in milliseconds spent processing the input prompt (tokenization + evaluation).
    /// </summary>
    public double PromptProcessingMs { get; set; }

    /// <summary>
    /// Time in milliseconds spent generating output tokens.
    /// </summary>
    public double GenerationMs { get; set; }

    /// <summary>
    /// Total end-to-end latency in milliseconds for the entire request.
    /// </summary>
    public double TotalLatencyMs { get; set; }

    /// <summary>
    /// Time from request sent to first output token received (TTFT - Time To First Token).
    /// </summary>
    public double FirstTokenLatencyMs { get; set; }
}
