namespace LR.Core.Models;

/// <summary>
/// A single chunk from a streaming inference request.
/// If IsFinal is true, Response contains the complete RouteResponse metadata.
/// Otherwise, TextDelta contains the incremental text token.
/// </summary>
public class RouteStreamChunk
{
    /// <summary>
    /// The incremental text content (token) for this chunk. Empty if IsFinal.
    /// </summary>
    public string TextDelta { get; set; } = string.Empty;

    /// <summary>
    /// True if this is the final chunk containing full response metadata.
    /// </summary>
    public bool IsFinal { get; set; }

    /// <summary>
    /// The complete route response (only populated when IsFinal is true).
    /// </summary>
    public RouteResponse? Response { get; set; }
}

/// <summary>
/// Wraps an inference response payload together with performance metadata returned by the backend provider.
/// </summary>
public class RouteResponse
{
    /// <summary>
    /// The text/content returned from the inference request.
    /// </summary>
    public string Payload { get; set; } = string.Empty;

    /// <summary>
    /// Number of tokens in the input prompt that were processed.
    /// </summary>
    public int PromptTokensProcessed { get; set; }

    /// <summary>
    /// Number of output tokens generated by the model.
    /// </summary>
    public int GeneratedTokenCount { get; set; }

    /// <summary>
    /// Time in milliseconds spent processing the input prompt (tokenization + evaluation).
    /// </summary>
    public double PromptProcessingMs { get; set; }

    /// <summary>
    /// Time in milliseconds spent generating output tokens.
    /// </summary>
    public double GenerationMs { get; set; }

    /// <summary>
    /// Total end-to-end latency in milliseconds for the entire request.
    /// </summary>
    public double TotalLatencyMs { get; set; }

    /// <summary>
    /// Time from request sent to first output token received (TTFT - Time To First Token).
    /// </summary>
    public double FirstTokenLatencyMs { get; set; }

    // --- Speculative decoding metrics (populated when speculative decoding is active) ---

    /// <summary>
    /// Draft acceptance rate for speculative decoding (0.0 to 1.0). Null if speculative decoding not used.
    /// </summary>
    public double? DraftAcceptanceRate { get; set; }

    /// <summary>
    /// Number of draft tokens accepted during speculative decoding.
    /// </summary>
    public int DraftAccepted { get; set; }

    /// <summary>
    /// Number of draft tokens generated during speculative decoding.
    /// </summary>
    public int DraftGenerated { get; set; }

    /// <summary>
    /// Raw timing data from the backend (e.g., llama-cpp-server timings object).
    /// Populated directly from the HTTP response for maximum fidelity — includes
    /// per-token and per-second metrics that don't fit in scalar properties.
    /// </summary>
    public OpenAI.LlamaCppTimings? BackendTimings { get; set; }

    /// <summary>
    /// Mean length of accepted draft sequences during speculative decoding.
    /// </summary>
    public double? DraftMeanLen { get; set; }
}
