using System.Text.Json;
using System.Text.Json.Serialization;

namespace LR.Core.Models.OpenAI;

/// <summary>
/// Streaming chunk for OpenAI-compatible chat completions (SSE).
/// </summary>
public class ChatCompletionChunk
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "chat.completion.chunk";

    [JsonPropertyName("created")]
    public long Created { get; set; }

    [JsonPropertyName("model")]
    public string Model { get; set; } = string.Empty;

    [JsonPropertyName("choices")]
    public List<ChunkChoice> Choices { get; set; } = new();

    /// <summary>
    /// A unique fingerprint of the system that generated the response.
    /// </summary>
    [JsonPropertyName("system_fingerprint")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? SystemFingerprint { get; set; }

    /// <summary>
    /// The service tier used for this request (e.g., "auto" or "default").
    /// </summary>
    [JsonPropertyName("service_tier")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ServiceTier { get; set; }

    /// <summary>
    /// Usage information included in the final chunk when stream_options.include_usage is true.
    /// Omitted (not null) on every other chunk — some client SDKs validate this field as
    /// present-with-value-or-absent rather than nullable, and choke on a literal null.
    /// </summary>
    [JsonPropertyName("usage")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Usage? Usage { get; set; }

    /// <summary>
    /// Timing information from llama.cpp backends (non-standard, kept for compatibility).
    /// </summary>
    [JsonPropertyName("timings")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public LlamaCppTimings? Timings { get; set; }
}

public class ChunkChoice
{
    [JsonPropertyName("index")]
    public int Index { get; set; }

    [JsonPropertyName("delta")]
    public DeltaMessage Delta { get; set; } = new();

    /// <summary>
    /// Log probability information for this delta.
    /// </summary>
    [JsonPropertyName("logprobs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ChoiceLogprobs? Logprobs { get; set; }

    /// <summary>
    /// The reason the model stopped generating tokens.
    /// </summary>
    [JsonPropertyName("finish_reason")]
    public string? FinishReason { get; set; }
}

/// <summary>
/// A partial (delta) message in a streaming response.
/// </summary>
public class DeltaMessage
{
    // Omitted (not null) on every chunk after the first — matches real OpenAI/llama.cpp wire
    // format, where "role" only appears once. Some client SDKs treat an unexpected literal
    // null here (and on the fields below) as a schema violation and drop the whole chunk.
    [JsonPropertyName("role")]
    [JsonConverter(typeof(StringOrFunctionConverter))]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Role { get; set; }

    /// <summary>
    /// The contents of the delta. Can be text or content parts.
    /// Uses the same polymorphic converter as ChatMessage.Content.
    /// </summary>
    [JsonPropertyName("content")]
    [JsonConverter(typeof(ChatMessageContentConverter))]
    public ChatMessageContent? Content { get; set; }

    /// <summary>
    /// Reasoning/thinking content generated by the model in this delta.
    /// Used for models with reasoning capabilities (e.g., DeepSeek R1, GPT-5 with reasoning).
    /// </summary>
    [JsonPropertyName("reasoning_content")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ReasoningContent { get; set; }

    /// <summary>
    /// Tool calls generated by the model in this delta.
    /// </summary>
    [JsonPropertyName("tool_calls")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<ChatToolCall>? ToolCalls { get; set; }

    /// <summary>
    /// Refusal text generated by the model in this delta.
    /// </summary>
    [JsonPropertyName("refusal")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Refusal { get; set; }
}
