using System.Text.Json;
using System.Text.Json.Serialization;

namespace LR.Core.Models.OpenAI;

/// <summary>
/// A single message in a chat conversation.
/// </summary>
public class ChatMessage
{
    /// <summary>
    /// The role of the messages author (system, user, assistant, tool).
    /// </summary>
    [JsonPropertyName("role")]
    [JsonConverter(typeof(StringOrFunctionConverter))]
    public string Role { get; set; } = string.Empty;

    /// <summary>
    /// The contents of the message. Can be a string, null, or an array of content parts.
    /// This uses a custom converter to handle polymorphic deserialization.
    /// </summary>
    [JsonPropertyName("content")]
    [JsonConverter(typeof(ChatMessageContentConverter))]
    public ChatMessageContent? Content { get; set; }

    /// <summary>
    /// The name of the author of this message (for function/tool calls).
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>
    /// The tool calls generated by the model (assistant messages only).
    /// </summary>
    [JsonPropertyName("tool_calls")]
    public List<ChatToolCall>? ToolCalls { get; set; }

    /// <summary>
    /// The ID of the tool call that this message is a response to (tool messages only).
    /// </summary>
    [JsonPropertyName("tool_call_id")]
    public string? ToolCallId { get; set; }

    /// <summary>
    /// The refusal message generated by the model (assistant messages only).
    /// </summary>
    [JsonPropertyName("refusal")]
    public string? Refusal { get; set; }

    /// <summary>
    /// Reasoning/thinking content generated by the model (assistant messages only, non-streaming).
    /// </summary>
    [JsonPropertyName("reasoning_content")]
    public string? ReasoningContent { get; set; }

    /// <summary>
    /// Audio output reference for this message.
    /// </summary>
    [JsonPropertyName("audio")]
    public ChatAudioOutput? Audio { get; set; }
}

/// <summary>
/// Polymorphic content for a chat message. Can be text or an array of content parts.
/// </summary>
public class ChatMessageContent
{
    private ChatMessageContent() { }

    /// <summary>Plain text content.</summary>
    public string? Text { get; internal set; }

    /// <summary>Array of content parts (multimodal).</summary>
    public List<ChatMessageContentPart>? Parts { get; internal set; }

    /// <summary>Create content from a plain text string.</summary>
    public static ChatMessageContent FromText(string text) => new() { Text = text };

    /// <summary>Create content from an array of parts.</summary>
    public static ChatMessageContent FromParts(List<ChatMessageContentPart> parts) => new() { Parts = parts };
}

/// <summary>
/// A single part in a multimodal message.
/// </summary>
public class ChatMessageContentPart
{
    /// <summary>The type of content part: "text", "image_url", "input_audio", or "input_file".</summary>
    [JsonPropertyName("type")]
    [JsonConverter(typeof(StringOrFunctionConverter))]
    public string Type { get; set; } = "text";

    /// <summary>Text content when type is "text".</summary>
    [JsonPropertyName("text")]
    public string? Text { get; set; }

    /// <summary>Image URL when type is "image_url".</summary>
    [JsonPropertyName("image_url")]
    public ChatImageUrlInput? ImageUrl { get; set; }

    /// <summary>Audio input when type is "input_audio".</summary>
    [JsonPropertyName("input_audio")]
    public ChatInputAudio? InputAudio { get; set; }

    /// <summary>File input when type is "input_file".</summary>
    [JsonPropertyName("input_file")]
    public ChatInputFile? InputFile { get; set; }
}

/// <summary>
/// Image URL for multimodal input.
/// </summary>
public class ChatImageUrlInput
{
    /// <summary>The URL of the image (data URI or HTTP/HTTPS URL).</summary>
    [JsonPropertyName("url")]
    public string Url { get; set; } = string.Empty;

    /// <summary>Specifies the detail level: "auto", "low", or "high".</summary>
    [JsonPropertyName("detail")]
    public string? Detail { get; set; }
}

/// <summary>
/// Audio input for multimodal requests.
/// </summary>
public class ChatInputAudio
{
    /// <summary>Base64-encoded audio data.</summary>
    [JsonPropertyName("data")]
    public string Data { get; set; } = string.Empty;

    /// <summary>The format of the audio data: "wav" or "mp3".</summary>
    [JsonPropertyName("format")]
    public string Format { get; set; } = "wav";
}

/// <summary>
/// File input for multimodal requests.
/// </summary>
public class ChatInputFile
{
    /// <summary>The ID of the file uploaded via the Files API.</summary>
    [JsonPropertyName("file_id")]
    public string FileId { get; set; } = string.Empty;

    /// <summary>Optional filename hint.</summary>
    [JsonPropertyName("filename")]
    public string? Filename { get; set; }

    /// <summary>Optional MIME type.</summary>
    [JsonPropertyName("mime_type")]
    public string? MimeType { get; set; }
}

/// <summary>
/// Audio output reference.
/// </summary>
public class ChatAudioOutput
{
    /// <summary>ID of the audio to be generated.</summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;
}

/// <summary>
/// Converter that returns a non-null default for string properties if the JSON value is null.
/// Used on "type", "role", and similar required-string properties to prevent llama.cpp from receiving null where it expects a string.
/// </summary>
public class StringOrFunctionConverter : JsonConverter<string>
{
    public override string Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.Null)
            return "function";

        if (reader.TokenType != JsonTokenType.String)
            throw new JsonException($"Expected string or null for property, got {reader.TokenType}");

        var value = reader.GetString();
        return string.IsNullOrEmpty(value) ? "function" : value;
    }

    public override void Write(Utf8JsonWriter writer, string value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(string.IsNullOrEmpty(value) ? "function" : value);
    }
}

/// <summary>
/// Custom JSON converter for polymorphic ChatMessageContent.
/// Handles: null, string (plain text), or array (content parts).
/// </summary>
public class ChatMessageContentConverter : JsonConverter<ChatMessageContent?>
{
    public override ChatMessageContent? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.Null)
            return null;

        if (reader.TokenType == JsonTokenType.String)
        {
            var text = reader.GetString();
            return string.IsNullOrEmpty(text) ? null : ChatMessageContent.FromText(text);
        }

        if (reader.TokenType == JsonTokenType.StartArray)
        {
            var parts = new List<ChatMessageContentPart>();
            while (reader.Read() && reader.TokenType != JsonTokenType.EndArray)
            {
                var part = JsonSerializer.Deserialize<ChatMessageContentPart>(ref reader, options);
                if (part is not null) parts.Add(part);
            }
            return ChatMessageContent.FromParts(parts);
        }

        throw new JsonException($"Unexpected token type {reader.TokenType} for ChatMessageContent");
    }

    public override void Write(Utf8JsonWriter writer, ChatMessageContent? value, JsonSerializerOptions options)
    {
        if (value is null)
        {
            writer.WriteNullValue();
            return;
        }

        if (value.Text is not null)
        {
            writer.WriteStringValue(value.Text);
            return;
        }

        if (value.Parts is { Count: > 0 })
        {
            JsonSerializer.Serialize(writer, value.Parts, options);
            return;
        }

        writer.WriteNullValue();
    }
}
