using System.Text.Json;
using System.Text.Json.Serialization;

namespace LR.Core.Models.OpenAI;

/// <summary>
/// A tool the model may call.
/// </summary>
public class ChatTool
{
    /// <summary>The type of the tool. Currently only "function" is supported.</summary>
    [JsonPropertyName("type")]
    [JsonConverter(typeof(StringOrFunctionConverter))]
    public string Type { get; set; } = "function";

    /// <summary>The function definition when type is "function".</summary>
    [JsonPropertyName("function")]
    public ChatToolFunction? Function { get; set; }
}

/// <summary>
/// A function definition for a tool.
/// </summary>
public class ChatToolFunction
{
    /// <summary>The name of the function to call.</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>An optional description of what the function does.</summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }

    /// <summary>The parameters the function accepts, as a JSON Schema object.</summary>
    [JsonPropertyName("parameters")]
    public JsonElement? Parameters { get; set; }
}

/// <summary>
/// A tool call generated by the model.
/// </summary>
public class ChatToolCall
{
    /// <summary>The ID of the tool call.</summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    /// <summary>The type of the tool. Currently only "function" is supported.</summary>
    [JsonPropertyName("type")]
    [JsonConverter(typeof(StringOrFunctionConverter))]
    public string Type { get; set; } = "function";

    /// <summary>The function that the model called.</summary>
    [JsonPropertyName("function")]
    public ChatToolCallFunction Function { get; set; } = new();
}

/// <summary>
/// The function details within a tool call.
/// </summary>
public class ChatToolCallFunction
{
    /// <summary>The name of the function to call.</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>The arguments to call the function with, as a JSON string.</summary>
    [JsonPropertyName("arguments")]
    public string Arguments { get; set; } = string.Empty;
}

/// <summary>
/// Specifies which tool the model should use.
/// Can be "none", "auto", "required", or an object specifying a specific tool.
/// </summary>
[JsonConverter(typeof(ChatToolChoiceConverter))]
public class ChatToolChoice
{
    /// <summary>When set to "none" the model will not call any tools.</summary>
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    /// <summary>When type is "function", specifies which function to call.</summary>
    [JsonPropertyName("function")]
    public ChatToolChoiceFunction? Function { get; set; }
}

/// <summary>
/// Converts between string and object representations of tool_choice.
/// OpenAI allows tool_choice to be a string ("none", "auto", "required") or an object.
/// </summary>
public class ChatToolChoiceConverter : JsonConverter<ChatToolChoice>
{
    public override ChatToolChoice? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.String)
        {
            var value = reader.GetString();
            return new ChatToolChoice { Type = value };
        }

        if (reader.TokenType == JsonTokenType.StartObject)
        {
            // Read object manually to avoid infinite recursion through the converter.
            string? type = null;
            ChatToolChoiceFunction? function = null;

            while (reader.Read())
            {
                if (reader.TokenType == JsonTokenType.EndObject)
                    break;

                if (reader.TokenType != JsonTokenType.PropertyName)
                    continue;

                var propertyName = reader.GetString();
                reader.Read();

                switch (propertyName)
                {
                    case "type":
                        type = reader.GetString();
                        break;
                    case "function":
                        function = JsonSerializer.Deserialize<ChatToolChoiceFunction>(ref reader, options);
                        break;
                }
            }

            return new ChatToolChoice { Type = type, Function = function };
        }

        throw new JsonException($"Unexpected token type: {reader.TokenType} for ChatToolChoice");
    }

    public override void Write(Utf8JsonWriter writer, ChatToolChoice value, JsonSerializerOptions options)
    {
        if (value.Function != null || (!string.IsNullOrEmpty(value.Type) && value.Type != "none" && value.Type != "auto" && value.Type != "required"))
        {
            // Write as object
            writer.WriteStartObject();
            if (!string.IsNullOrEmpty(value.Type))
                writer.WriteString("type", value.Type);
            if (value.Function != null)
            {
                writer.WritePropertyName("function");
                JsonSerializer.Serialize(writer, value.Function, options);
            }
            writer.WriteEndObject();
        }
        else
        {
            // Write as string ("none", "auto", "required")
            writer.WriteStringValue(value.Type ?? "auto");
        }
    }
}

/// <summary>
/// Specifies a specific function for the model to call.
/// </summary>
public class ChatToolChoiceFunction
{
    /// <summary>The name of the function to call.</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;
}

/// <summary>(Deprecated) A legacy function definition. Use <see cref="ChatTool"/> instead.</summary>
[Obsolete("Use ChatTool and ChatToolFunction instead.")]
public class ChatFunction
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("parameters")]
    public JsonElement? Parameters { get; set; }
}
