using System.Text.Json;
using System.Text.Json.Serialization;

using LR.Core.Models.OpenAI;

namespace LR.Core.Models.Ollama;

/// <summary>
/// Request body for Ollama chat API.
/// </summary>
public class ChatRequest
{
    /// <summary>
    /// The model to use. Should match a configured preset name.
    /// </summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = string.Empty;

    /// <summary>
    /// The conversation messages.
    /// </summary>
    [JsonPropertyName("messages")]
    public List<ChatMessage> Messages { get; set; } = new();

    /// <summary>
    /// Whether to stream the response as JSON lines. Defaults to true, matching Ollama's API behavior
    /// (a client that omits "stream" expects a streamed response).
    /// </summary>
    [JsonPropertyName("stream")]
    public bool Stream { get; set; } = true;

    /// <summary>
    /// Additional options for model inference.
    /// </summary>
    [JsonPropertyName("options")]
    public ChatOptions? Options { get; set; }

    /// <summary>
    /// A list of tools the model may call. Ollama's tool schema matches OpenAI's
    /// ("type": "function", "function": { name, description, parameters }), so the
    /// OpenAI model type is reused directly instead of duplicating it.
    /// </summary>
    [JsonPropertyName("tools")]
    public List<ChatTool>? Tools { get; set; }

    /// <summary>
    /// Ollama's reasoning toggle: a bool (thinking on/off, no discrete magnitude) or a string
    /// level ("low"/"medium"/"high") for models with graduated reasoning effort. Kept as raw
    /// JSON since which shape a client sends varies; only the string form maps onto a
    /// reasoning_effort value the backend chat template understands.
    /// </summary>
    [JsonPropertyName("think")]
    public JsonElement? Think { get; set; }
}

public class ChatMessage
{
    [JsonPropertyName("role")]
    public string Role { get; set; } = "user";

    [JsonPropertyName("content")]
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Tool calls generated by the model (assistant messages only).
    /// </summary>
    [JsonPropertyName("tool_calls")]
    public List<OllamaToolCall>? ToolCalls { get; set; }

    /// <summary>
    /// The name of the tool this message is a response from (tool messages only).
    /// This is Ollama's native way of correlating a tool result with the call that
    /// requested it, since Ollama historically didn't assign call IDs.
    /// </summary>
    [JsonPropertyName("tool_name")]
    public string? ToolName { get; set; }

    /// <summary>
    /// The ID of the tool call this message is a response to (tool messages only).
    /// Not part of Ollama's original schema, but some clients send it for
    /// OpenAI-style correlation; accepted here if present.
    /// </summary>
    [JsonPropertyName("tool_call_id")]
    public string? ToolCallId { get; set; }
}

/// <summary>
/// A tool call as represented in Ollama's chat protocol.
/// </summary>
public class OllamaToolCall
{
    /// <summary>The ID of the tool call, if the client assigns one.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("function")]
    public OllamaToolCallFunction Function { get; set; } = new();
}

/// <summary>
/// The function details within an Ollama tool call. Unlike OpenAI, Ollama represents
/// arguments as a JSON object rather than a JSON-encoded string.
/// </summary>
public class OllamaToolCallFunction
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("arguments")]
    public JsonElement Arguments { get; set; }
}

public class ChatOptions
{
    [JsonPropertyName("temperature")]
    public double? Temperature { get; set; }

    [JsonPropertyName("num_predict")]
    public int? NumPredict { get; set; }

    [JsonPropertyName("top_k")]
    public int? TopK { get; set; }

    [JsonPropertyName("top_p")]
    public double? TopP { get; set; }

    [JsonPropertyName("min_p")]
    public double? MinP { get; set; }

    [JsonPropertyName("repeat_penalty")]
    public double? RepeatPenalty { get; set; }

    [JsonPropertyName("presence_penalty")]
    public double? PresencePenalty { get; set; }

    [JsonPropertyName("frequency_penalty")]
    public double? FrequencyPenalty { get; set; }

    [JsonPropertyName("seed")]
    public int? Seed { get; set; }

    [JsonPropertyName("stop")]
    public string[]? Stop { get; set; }
}
